# Generated by Django 6.0.6 on 2026-08-25 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('subscribe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PinnedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pinned Post',
                'verbose_name_plural': 'Pinned Posts',
                'db_table': 'pinned_posts',
                'ordering': ['pinned_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('activated', 'Activated'), ('renewed', 'Renewed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('payment_failed', 'Payment_failed')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Subscription History',
                'verbose_name_plural': 'Subscription History',
                'db_table': 'subscription_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-created_at'], 'verbose_name': 'Subscription', 'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'status'], name='subscriptio_user_id_8d58fd_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['end_date', 'status'], name='subscriptio_end_dat_286f74_idx'),
        ),
        migrations.AlterModelTable(
            name='subscription',
            table='subscriptions',
        ),
        migrations.AddField(
            model_name='pinnedpost',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pin_info', to='main.post'),
        ),
        migrations.AddField(
            model_name='pinnedpost',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='subscribe.subscription'),
        ),
        migrations.AddIndex(
            model_name='pinnedpost',
            index=models.Index(fields=['pinned_at'], name='pinned_post_pinned__686558_idx'),
        ),
    ]
